### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by richardonrails** [jaredmdobson/rack-livereload#10]
It appears that [the rubygem](https://rubygems.org/gems/rack-livereload/) points to your fork now.

However the rubygem is currently showing `0.3.17` as the latest version. Your repo shows the latest tag as `0.3.17`. However your [code](https://github.com/jaredmdobson/rack-livereload/blob/5a743ff55a91bf890967f850f8e017253ed3dce2/lib/rack-livereload.rb#L4) shows a `0.4.2`.

Would you be able to push 0.4.2 to rubygems?

(Figured this out via https://github.com/guard/guard-livereload/issues/143#issuecomment-1341802770)

**Comment by jaredmdobson** [comment]
I'll check this out.

**Comment by Kulgar** [comment]
@jaredmdobson : if possible, I'd like to be added to the maintainers of the project :-) I could handle pushing to rubygems 

I don't want to be the new owner of the project though - unless you really don't want to be the owner anymore. 

Thx!

**Comment by jaredmdobson** [comment]
@Kulgar i added you and i can add your email to our rubygem project.

**Comment by Kulgar** [comment]
@jaredmdobson  yes please, add my email to the rubygem project :-) I'll gladly push the new releases, thx!!

**Comment by jaredmdobson** [comment]
Done :)
