### ISSUE TITLE
Rack 3.1 compatibility

### ISSUE THREAD

**Issue by Fjan** [jaredmdobson/rack-livereload#19]
Currently, the gemspec locks to `rack ~> 3.0.8`, this means we cannot update to the latest rack version 3.1. As far as I can tell rack version 3.1 is a maintenance release with no features that should affect rack-livereload. Can we please update the gem spec to allow the new version to be used? For example, `"rack", ">= 3.0", "< 3.2"`

**Comment by jaredmdobson** [comment]
Let me know if 0.6.1 works for you.

**Comment by Fjan** [comment]
Thanks!
